[build]
  publish = "dist"
  functions = "src/functions"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  functions = "src/functions"

[[redirects]]
  from = "/about"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/skills"
  to = "/skills/index.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/projects/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact/index.html"
  status = 200

[[redirects]]
  from = "/posts"
  to = "/notes"
  status = 301
  force = true

[[redirects]]
  from = "/notes"
  to = "/notes/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/dashboard"
  to = "/admin/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
